/**
 * Conference programme data from the official WILDE Student Conference schedule.
 *
 * Room numbers are not listed in the source schedule, so sessions use the
 * published tracks: Main, Parallel 1, Parallel 2.
 *
 * Add resource people under `people` and list their ids on each session’s
 * `people` array. Photos go in assets/people/.
 */
window.WILDE_PROGRAMME = {
  note:
    "Official programme from the WILDE Student Conference schedule. Room numbers and resource-person names will be added when confirmed. Organised by Saryan Vigyan Foundation and G.B. Pant Memorial Govt. College, Rampur.",
  organizers: [
    {
      id: "saryan",
      name: "Saryan Vigyan Foundation",
      shortName: "Saryan Vigyan Foundation",
      role: "Organiser",
      address:
        "Village & PO Ralli (Mebar), Tehsil Kalpa, District Kinnaur, Himachal Pradesh 172107",
      website: "https://www.saryanfoundation.org/",
      email: "saryanfoundation@gmail.com",
      phone: "",
      logo: "assets/organizers/saryan-logo.png",
      blurb:
        "A non-profit working on biodiversity conservation in the Indian Himalayan Region through science, research, and community collaboration.",
    },
    {
      id: "gbpant",
      name: "G.B. Pant Memorial Govt. College",
      shortName: "GB Pant College, Rampur",
      role: "Host college",
      address: "Rampur Bushahr, District Shimla, Himachal Pradesh 172001",
      website: "https://gbpmgcrampur.edu.in/",
      email: "gcrampur59@gmail.com",
      phone: "+91 1782 233021",
      logo: "assets/organizers/college-logo.png",
      blurb:
        "Host campus for the WILDE-Student Conference in Rampur Bushahr.",
    },
  ],
  people: [],
  sessions: [
    {
      id: "d1-registration",
      title: "Registration",
      type: "registration",
      workshop: null,
      date: "2026-11-15",
      start: "09:00",
      end: "10:00",
      room: "Main",
      people: [],
      summary: "Arrive, register, and collect conference information.",
      access: "open",
    },
    {
      id: "d1-inauguration",
      title: "Inauguration",
      type: "ceremony",
      workshop: null,
      date: "2026-11-15",
      start: "10:00",
      end: "10:30",
      room: "Main",
      people: [],
      summary: "Opening of the WILDE Student Conference.",
      access: "open",
    },
    {
      id: "d1-talks",
      title: "Talks",
      type: "talk",
      workshop: null,
      date: "2026-11-15",
      start: "10:30",
      end: "11:30",
      room: "Main",
      people: [],
      summary: "Open to all students, even without registration.",
      access: "open",
    },
    {
      id: "d1-ws-posh",
      title: "Workshop 1 · POSH for students",
      code: "Workshop-1",
      type: "workshop",
      workshop: "POSH for students",
      date: "2026-11-15",
      start: "11:30",
      end: "13:00",
      room: "Main",
      people: [],
      summary: "Workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d1-ws-insects",
      title: "WS-2 · Know insects around you",
      code: "WS-2",
      type: "workshop",
      workshop: "Know insects around you",
      date: "2026-11-15",
      start: "11:30",
      end: "13:00",
      room: "Parallel 1",
      people: [],
      summary: "Parallel workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d1-ws-career",
      title: "WS-3 · Career growth with interdisciplinary subjects",
      code: "WS-3",
      type: "workshop",
      workshop: "Career growth with interdisciplinary subjects",
      date: "2026-11-15",
      start: "11:30",
      end: "13:00",
      room: "Parallel 2",
      people: [],
      summary: "Parallel workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d1-lunch",
      title: "Lunch",
      type: "break",
      workshop: null,
      date: "2026-11-15",
      start: "13:00",
      end: "14:00",
      room: "Main",
      people: [],
      summary: "Lunch break.",
      access: "open",
    },
    {
      id: "d1-ws-r",
      title: "WS-1 · Basic statistics with R for all",
      code: "WS-1",
      type: "workshop",
      workshop: "Basic statistics with R for all",
      date: "2026-11-15",
      start: "14:00",
      end: "16:00",
      room: "Main",
      people: [],
      summary: "Workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d1-ws-gis",
      title: "WS-4 · GIS–QGIS",
      code: "WS-4",
      type: "workshop",
      workshop: "GIS–QGIS",
      date: "2026-11-15",
      start: "14:00",
      end: "16:00",
      room: "Parallel 1",
      people: [],
      summary: "Parallel workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d1-ws-biomed",
      title: "WS-5 · Bio-medical engineering",
      code: "WS-5",
      type: "workshop",
      workshop: "Bio-medical engineering",
      date: "2026-11-15",
      start: "14:00",
      end: "16:00",
      room: "Parallel 2",
      people: [],
      summary: "Parallel workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d1-networking",
      title: "Networking, poster and tea",
      type: "networking",
      workshop: null,
      date: "2026-11-15",
      start: "16:00",
      end: "17:30",
      room: "Main",
      people: [],
      summary: "Posters, informal networking, and tea.",
      access: "open",
    },
    {
      id: "d2-registration",
      title: "Registration",
      type: "registration",
      workshop: null,
      date: "2026-11-16",
      start: "09:00",
      end: "10:00",
      room: "Main",
      people: [],
      summary: "Day 2 registration and arrival.",
      access: "open",
    },
    {
      id: "d2-talks",
      title: "Talks",
      type: "talk",
      workshop: null,
      date: "2026-11-16",
      start: "10:30",
      end: "11:30",
      room: "Main",
      people: [],
      summary: "Open to all students, even without registration.",
      access: "open",
    },
    {
      id: "d2-science-together",
      title: "Activity · Science together",
      type: "activity",
      workshop: "Science together",
      date: "2026-11-16",
      start: "11:30",
      end: "13:00",
      room: "Main",
      people: [],
      summary: "Group activity for registered participants.",
      access: "registered",
    },
    {
      id: "d2-explain-5yo",
      title: "Activity · Explain a concept to a 5-year-old",
      type: "activity",
      workshop: "Explain a concept to a 5-year-old",
      date: "2026-11-16",
      start: "11:30",
      end: "13:00",
      room: "Parallel 1",
      people: [],
      summary: "Parallel activity for registered participants.",
      access: "registered",
    },
    {
      id: "d2-ws-photo",
      title: "WS-6 · Photography for communication",
      code: "WS-6",
      type: "workshop",
      workshop: "Photography for communication",
      date: "2026-11-16",
      start: "11:30",
      end: "13:00",
      room: "Parallel 2",
      people: [],
      summary: "Parallel workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d2-lunch",
      title: "Lunch",
      type: "break",
      workshop: null,
      date: "2026-11-16",
      start: "13:00",
      end: "14:00",
      room: "Main",
      people: [],
      summary: "Lunch break.",
      access: "open",
    },
    {
      id: "d2-ws-drawing",
      title: "WS-8 · Communicating via line drawing",
      code: "WS-8",
      type: "workshop",
      workshop: "Communicating via line drawing",
      date: "2026-11-16",
      start: "14:00",
      end: "15:30",
      room: "Main",
      people: [],
      summary: "Workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d2-ws-writing",
      title: "WS-9 · Science communication via writing",
      code: "WS-9",
      type: "workshop",
      workshop: "Science communication via writing",
      date: "2026-11-16",
      start: "14:00",
      end: "15:30",
      room: "Parallel 1",
      people: [],
      summary: "Parallel workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d2-ws-citizen",
      title: "WS-10 · Citizen science projects and scope",
      code: "WS-10",
      type: "workshop",
      workshop: "Citizen science projects and scope",
      date: "2026-11-16",
      start: "14:00",
      end: "15:30",
      room: "Parallel 2",
      people: [],
      summary: "Parallel workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d2-ws-hypothesis",
      title: "WS-7 · Hypothesis testing and experiment design",
      code: "WS-7",
      type: "workshop",
      workshop: "Hypothesis testing and experiment design",
      date: "2026-11-16",
      start: "15:30",
      end: "17:00",
      room: "Main",
      people: [],
      summary: "Workshop for registered participants.",
      access: "registered",
    },
    {
      id: "d2-closing",
      title: "Prize announcement and closing ceremony",
      type: "ceremony",
      workshop: null,
      date: "2026-11-16",
      start: "17:00",
      end: "17:30",
      room: "Main",
      people: [],
      summary: "Closing of the conference and prize announcement.",
      access: "open",
    },
  ],
};
